### ISSUE TITLE
Add IO functions to read and write WKT and WKB

### ISSUE THREAD

**Issue by jorisvandenbossche** [benbovy/spherely#38]
We should have functions to create geographies from WKT and WKB, and also to convert to WKT and WKB.

(similarly to shapely's `from_wkt`/`from_wkb` and `to_wkt`/`to_wkb`)

At the moment `s2geography` does have a basic WKTWriter (which we already use in `__repr__`) and WKTReader, but proper (and easier) support probably depends on https://github.com/paleolimbot/s2geography/pull/16

**Comment by benbovy** [comment]
Some naive questions as I'm not very familiar yet with (geo)arrow. 

IIUC https://github.com/paleolimbot/s2geography/pull/16 adds support for Arrow arrays so that we can easily reuse all the work done in geoarrow (and its implementation geoarrow-c) for parsing / encoding simple feature geometries.

- We want to support Numpy arrays for IO functions. So I guess we would need to internally convert Numpy <-> Arrow arrays to support that? How expensive would it be?
- Do we want direct support for Arrow arrays in Spherely IO functions? This could be useful I guess, even though other vectorized "universal" functions in Spherely would still support Numpy arrays only. Or maybe it would make sense to support Arrow arrays everywhere and internally convert to Numpy arrays when needed?
- Should we reuse geoarrow as well for coordinate operations (i.e., `get_coordinates`) to avoid reinventing the wheel, or would #37 be straightforward to extent to other geometries?
